import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.food": "Food",
    "nav.services": "Services",
    "nav.community": "Community",
    "nav.myOrders": "My Orders",
    "nav.myRestaurant": "My Restaurant",
    "nav.myServices": "My Services",
    "nav.getStarted": "Get Started",
    "nav.logout": "Log out",
    "nav.switchAccount": "Switch Account",
    "nav.restaurantPortal": "Restaurant Portal",
    "nav.serviceProviderPortal": "Service Provider Portal",
    "nav.myBookings": "My Bookings",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.restaurantVendor": "Restaurant Vendor",
    "nav.serviceProvider": "Service Provider",
    "nav.customer": "Customer",

    "landing.aboutTitle": "About BrazaDash",
    "landing.aboutDesc": "BrazaDash.com is a platform created to connect, support, and empower the Brazilian community, bringing together businesses, restaurants, service providers, and customers in one centralized digital space.",
    "landing.aboutMissionTitle": "Our mission is simple:",
    "landing.aboutMission": "Strengthen our community by making Brazilian products, services, culture, and events more accessible and visible to everyone.",
    "landing.aboutClosing": "BrazaDash is more than a marketplace — it's a community meeting point where people can discover, engage, and support Brazilian entrepreneurship and culture.",
    "landing.exploreFood": "Explore Food",
    "landing.exploreServices": "Explore Services",
    "landing.exploreCommunity": "Explore Community",

    "landing.badge": "Now serving California",
    "landing.heroTitle1": "Brazilian flavor",
    "landing.heroTitle2": "at your door",
    "landing.heroDesc": "Discover authentic Brazilian cuisine from your favorite restaurants. From feijoada to pao de queijo, experience the taste of Brazil right here in California.",
    "landing.orderNow": "Order Now",
    "landing.learnMore": "Learn More",
    "landing.securePayments": "Secure payments",
    "landing.fastDelivery": "Fast delivery",
    "landing.rating": "4.9 Rating",
    "landing.happyCustomers": "10k+ happy customers",
    "landing.whyChoose": "Why choose",
    "landing.whyChooseDesc": "We bring the authentic taste of Brazil to your doorstep with care and quality.",
    "landing.authenticCuisine": "Authentic Brazilian Cuisine",
    "landing.authenticCuisineDesc": "From traditional feijoada to street-style coxinhas, experience genuine Brazilian flavors prepared by passionate cooks.",
    "landing.localCommunity": "Local Community",
    "landing.localCommunityDesc": "Connect with Brazilian restaurants and home cooks right in your neighborhood. Support your local community.",
    "landing.fastDeliveryTitle": "Fast Delivery",
    "landing.fastDeliveryDesc": "Get your favorite Brazilian dishes delivered hot and fresh. Track your order in real-time from kitchen to door.",
    "landing.verifiedReviews": "Verified Reviews",
    "landing.verifiedReviewsDesc": "Make informed decisions with honest reviews from real customers. Every rating is from a verified order.",
    "landing.securePaymentsTitle": "Secure Payments",
    "landing.securePaymentsDesc": "Your transactions are protected with industry-standard encryption. Pay with confidence using your preferred method.",
    "landing.madeWithLove": "Made with Love",
    "landing.madeWithLoveDesc": "Every dish is prepared with the same love and care as a Brazilian home-cooked meal. Saudade never tasted so good.",
    "landing.readyToTaste": "Ready to taste Brazil?",
    "landing.readyToTasteDesc": "Join thousands of Brazilians in California enjoying authentic food from the comfort of their homes.",
    "landing.getStartedFree": "Get Started - It's Free",
    "landing.footer": "\u00a9 2024 BrazaDash. Made with love for the Brazilian community.",

    "onboarding.welcome": "Welcome to BrazaDash!",
    "onboarding.subtitle": "Welcome! How would you like to use the platform?",
    "onboarding.subtitlePt": "Como voc\u00ea gostaria de usar a plataforma?",
    "onboarding.customer": "Customer",
    "onboarding.customerSub": "Buy",
    "onboarding.customerDesc": "Browse restaurants, order food, book services, and explore the community.",
    "onboarding.vendor": "Restaurant / Food Vendor",
    "onboarding.vendorSub": "Sell Food",
    "onboarding.vendorDesc": "Manage your restaurant, create menus, and process food orders from customers.",
    "onboarding.provider": "Service Provider",
    "onboarding.providerSub": "Offer Services",
    "onboarding.providerDesc": "List your professional services, manage bookings, and grow your client base.",
    "onboarding.continue": "Continue",
    "onboarding.next": "Next",
    "onboarding.back": "Back",
    "onboarding.submit": "Submit Registration",
    "onboarding.submitting": "Submitting...",
    "onboarding.settingUp": "Setting up your account...",
    "onboarding.changeRole": "You can contact support later if you need to change your role.",
    "onboarding.welcomeToast": "Welcome to BrazaDash!",
    "onboarding.welcomeToastDesc": "Your account is ready. Let's get started!",
    "onboarding.error": "Something went wrong",
    "onboarding.errorDesc": "Please try again.",
    "onboarding.step1": "Choose Your Role",
    "onboarding.step2": "Business Information",
    "onboarding.vendorInfoTitle": "Tell us about your restaurant",
    "onboarding.vendorInfoDesc": "This information will be reviewed by our team before your restaurant goes live.",
    "onboarding.providerInfoTitle": "Tell us about your services",
    "onboarding.providerInfoDesc": "This information will be reviewed by our team before your profile goes live.",
    "onboarding.restaurantName": "Restaurant Name",
    "onboarding.restaurantNamePlaceholder": "e.g. Sabor do Brasil",
    "onboarding.businessDescription": "Description",
    "onboarding.businessDescriptionPlaceholder": "Describe your restaurant and what makes it special...",
    "onboarding.cuisine": "Cuisine Type",
    "onboarding.cuisinePlaceholder": "e.g. Brazilian, Churrasco, Bakery",
    "onboarding.city": "City",
    "onboarding.cityPlaceholder": "e.g. San Francisco",
    "onboarding.address": "Address",
    "onboarding.addressPlaceholder": "Street address",
    "onboarding.phone": "Phone Number",
    "onboarding.phonePlaceholder": "(555) 123-4567",
    "onboarding.businessName": "Business Name",
    "onboarding.businessNamePlaceholder": "e.g. Maria's Cleaning Services",
    "onboarding.providerDescriptionPlaceholder": "Describe the services you offer...",
    "onboarding.category": "Service Category",
    "onboarding.categoryPlaceholder": "Select a category",
    "onboarding.email": "Business Email",
    "onboarding.emailPlaceholder": "contact@yourbusiness.com",
    "onboarding.categoryCleaning": "Cleaning",
    "onboarding.categoryBeauty": "Beauty",
    "onboarding.categoryLegal": "Legal",
    "onboarding.categoryFitness": "Fitness",
    "onboarding.categoryAuto": "Auto",
    "onboarding.categoryConstruction": "Construction",
    "onboarding.categoryOther": "Other",
    "onboarding.required": "Required",

    "home.badge": "Brazilian Community in California",
    "home.greeting": "Hello",
    "home.welcomeTo": "Welcome to BrazaDash",
    "home.heroDesc": "Your connection to the Brazilian community in California. Discover authentic restaurants, find trusted services, and connect with our community.",
    "home.orderFood": "Order Food",
    "home.findServices": "Find Services",
    "home.community": "Community",
    "home.popularServices": "Popular Services",
    "home.popularServicesDesc": "Popular services from our Brazilian community",
    "home.viewAll": "View All",
    "home.featuredProviders": "Featured Providers",
    "home.featuredRestaurants": "Featured Restaurants",
    "home.featuredRestaurantsDesc": "Discover the best Brazilian food in your area",
    "home.noRestaurants": "No restaurants yet",
    "home.noRestaurantsDesc": "Be the first to add your restaurant to BrazaDash!",
    "home.becomeVendor": "Become a Vendor",
    "home.testimonialsBadge": "Community Testimonials",
    "home.testimonialsTitle": "What Our Community Says",
    "home.testimonialsDesc": "What our community says about BrazaDash",
    "home.recentReviews": "Recent Reviews",
    "home.recentReviewsDesc": "Latest reviews from the community",
    "home.communityHub": "Community Hub",
    "home.upcomingEvents": "Upcoming Events",
    "home.viewAllEvents": "View all events",
    "home.noEvents": "No upcoming events",
    "home.businessDirectory": "Business Directory",
    "home.viewAllBusinesses": "View all businesses",
    "home.noBusinesses": "No businesses listed yet",
    "home.announcements": "Announcements",
    "home.noAnnouncements": "No announcements",
    "home.open": "Open",
    "home.closed": "Closed",
    "home.delivery": "delivery",
    "home.verified": "Verified",
    "home.food": "Food",
    "home.service": "Service",

    "home.cleaning": "Cleaning",
    "home.beauty": "Beauty",
    "home.legal": "Legal",
    "home.fitness": "Fitness",
    "home.auto": "Auto",
    "home.construction": "Construction",

    "restaurants.title": "Brazilian Restaurants",
    "restaurants.subtitle": "Discover authentic Brazilian food in your area",
    "restaurants.search": "Search restaurants...",
    "restaurants.all": "All",
    "restaurants.noResults": "No restaurants found",
    "restaurants.noResultsDesc": "Try adjusting your search or filter criteria.",
    "restaurants.open": "Open",
    "restaurants.closed": "Closed",

    "services.title": "Brazilian Services",
    "services.subtitle": "Find trusted Brazilian service providers in your area",
    "services.search": "Search services...",
    "services.allCategories": "All Categories",
    "services.noResults": "No service providers found",
    "services.noResultsDesc": "Try adjusting your search or filter criteria.",
    "services.startingAt": "Starting at",
    "services.viewProfile": "View Profile",
    "services.verified": "Verified",
    "services.reviews": "reviews",

    "community.title": "Community Hub",
    "community.subtitle": "Connect with the Brazilian community in California",
    "community.events": "Events",
    "community.businesses": "Businesses",
    "community.announcements": "Announcements",
    "community.featuredEvents": "Featured Events",
    "community.upcomingEvents": "Upcoming Events",
    "community.viewAllEvents": "View All Events",
    "community.noEvents": "No events found",
    "community.noEventsDesc": "Check back soon for upcoming community events!",
    "community.rsvp": "RSVP",
    "community.attending": "attending",
    "community.free": "Free",
    "community.yellowPages": "Yellow Pages",
    "community.yellowPagesDesc": "Rooms, houses, apartments, cars, and more",
    "community.viewYellowPages": "Browse Listings",
    "community.browseYellowPages": "Browse Yellow Pages",
    "community.addEvent": "Add Event",
    "community.latestAnnouncements": "Latest Announcements",

    "yp.title": "Yellow Pages",
    "yp.subtitle": "Find rooms, houses, apartments, cars, and more from the Brazilian community",
    "yp.addListing": "Add Listing",
    "yp.newListing": "New Listing",
    "yp.listingTitle": "Title",
    "yp.titlePlaceholder": "e.g. Room for rent in Los Angeles",
    "yp.category": "Category",
    "yp.description": "Description",
    "yp.descriptionPlaceholder": "Describe what you are offering...",
    "yp.price": "Price",
    "yp.city": "City",
    "yp.address": "Address",
    "yp.addressPlaceholder": "Street address (optional)",
    "yp.contactName": "Contact Name",
    "yp.contactPhone": "Phone",
    "yp.contactEmail": "Email",
    "yp.allCities": "All Cities",
    "yp.all": "All",
    "yp.searchPlaceholder": "Search listings...",
    "yp.noListings": "No listings found",
    "yp.noListingsFiltered": "No listings match your filters. Try adjusting your search.",
    "yp.noListingsYet": "No listings yet. Be the first to post!",
    "yp.submit": "Submit Listing",
    "yp.submitting": "Submitting...",
    "yp.submitSuccess": "Listing Submitted",
    "yp.submitSuccessDesc": "Your listing has been submitted and is pending admin approval.",
    "yp.submitError": "Error",
    "yp.submitErrorDesc": "Failed to submit listing. Please try again.",
    "yp.approvalNotice": "All listings require admin approval before becoming visible.",
    "yp.listingImage": "Photo",
    "yp.imageRecommendation": "Recommended size: 1200 x 630 pixels (landscape). Images will be resized to fit the card layout uniformly.",
    "yp.uploadImage": "Click to upload photo",
    "yp.uploadingImage": "Uploading...",
    "yp.imageUploaded": "Photo Uploaded",
    "yp.imageUploadedDesc": "Your photo has been uploaded successfully.",
    "yp.imageUploadError": "Failed to upload photo. Please try again.",

    "events.addEvent": "Add Event",
    "events.newEvent": "New Event",
    "events.eventTitle": "Event Title",
    "events.eventTitlePlaceholder": "e.g. Brazilian BBQ Night",
    "events.eventCategory": "Category",
    "events.eventDescription": "Description",
    "events.eventDescriptionPlaceholder": "Describe your event...",
    "events.eventDate": "Event Date",
    "events.startTime": "Start Time",
    "events.endTime": "End Time",
    "events.venue": "Venue",
    "events.venuePlaceholder": "e.g. Central Park",
    "events.eventCity": "City",
    "events.isFree": "Free Event",
    "events.ticketPrice": "Ticket Price",
    "events.ticketUrl": "Ticket URL",
    "events.submitEvent": "Submit Event",
    "events.submittingEvent": "Submitting...",
    "events.submitEventSuccess": "Event Submitted",
    "events.submitEventSuccessDesc": "Your event has been submitted and is pending admin approval.",
    "events.submitEventError": "Error",
    "events.submitEventErrorDesc": "Failed to submit event. Please try again.",
    "events.approvalNotice": "All events require admin approval before becoming visible.",
    "events.eventImage": "Event Image",
    "events.imageRecommendation": "Recommended size: 1200 x 630 pixels (landscape). Images will be resized to fit the card layout uniformly.",
    "events.uploadImage": "Click to upload image",
    "events.uploadingImage": "Uploading...",
    "events.imageUploaded": "Image Uploaded",
    "events.imageUploadedDesc": "Your image has been uploaded successfully.",
    "events.imageUploadError": "Failed to upload image. Please try again.",
    "community.noAnnouncements": "No announcements",
    "community.noAnnouncementsDesc": "Check back soon for community announcements!",

    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Looks like you haven't added any items yet. Explore our delicious Brazilian restaurants!",
    "cart.browseRestaurants": "Browse Restaurants",
    "cart.orderFrom": "Order from",
    "cart.items": "Items",
    "cart.clearCart": "Clear Cart",
    "cart.subtotal": "Subtotal",
    "cart.deliveryFee": "Delivery Fee",
    "cart.total": "Total",
    "cart.proceedToCheckout": "Proceed to Checkout",
    "cart.remove": "Remove",

    "orders.title": "My Orders",
    "orders.subtitle": "Track your food orders and delivery status",
    "orders.noOrders": "No orders yet",
    "orders.noOrdersDesc": "Start exploring our restaurants and place your first order!",
    "orders.browseRestaurants": "Browse Restaurants",
    "orders.orderNumber": "Order",
    "orders.items": "items",
    "orders.viewDetails": "View Details",
    "orders.pending": "Pending",
    "orders.confirmed": "Confirmed",
    "orders.preparing": "Preparing",
    "orders.ready": "Ready",
    "orders.outForDelivery": "Out for Delivery",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",

    "vendor.dashboard": "Restaurant Dashboard",
    "vendor.createRestaurant": "Create Your Restaurant",
    "vendor.restaurantName": "Restaurant Name",
    "vendor.description": "Description",
    "vendor.cuisine": "Cuisine Type",
    "vendor.address": "Address",
    "vendor.phone": "Phone",
    "vendor.deliveryFee": "Delivery Fee",
    "vendor.create": "Create Restaurant",
    "vendor.creating": "Creating...",
    "vendor.orders": "Orders",
    "vendor.menu": "Menu",
    "vendor.newOrders": "New Orders",
    "vendor.activeOrders": "Active Orders",
    "vendor.completed": "Completed",
    "vendor.noOrders": "No orders yet",
    "vendor.accept": "Accept Order",
    "vendor.decline": "Decline",
    "vendor.startPreparing": "Start Preparing",
    "vendor.readyForPickup": "Ready for Pickup",
    "vendor.outForDelivery": "Out for Delivery",
    "vendor.markDelivered": "Mark Delivered",
    "vendor.addMenuItem": "Add Item",
    "vendor.itemName": "Item Name",
    "vendor.price": "Price",
    "vendor.category": "Category",
    "vendor.save": "Save",
    "vendor.pending": "Pending",
    "vendor.active": "Active",
    "vendor.rating": "Rating",
    "vendor.menuItems": "Menu Items",
    "vendor.restaurantOpen": "Restaurant is open",
    "vendor.restaurantClosed": "Restaurant is closed",
    "vendor.newOrder": "New Order",
    "vendor.orderConfirmed": "Confirmed",
    "vendor.orderPreparing": "Preparing",
    "vendor.orderReady": "Ready for Pickup",
    "vendor.orderOutForDelivery": "Out for Delivery",
    "vendor.orderDelivered": "Delivered",
    "vendor.orderCancelled": "Cancelled",
    "vendor.quantity": "Availability (Quantity)",
    "vendor.quantityPlaceholder": "Leave empty for unlimited",
    "vendor.quantityHint": "Set the number of servings available. Leave empty for unlimited.",
    "vendor.itemImage": "Item Image",
    "vendor.uploadImage": "Click to upload an image",
    "vendor.uploadImageHint": "JPEG, PNG, WebP or GIF (max 5MB)",
    "vendor.imageUploaded": "Image uploaded successfully",
    "vendor.imageUploadError": "Failed to upload image",
    "vendor.removeImage": "Remove",
    "vendor.menuItemAdded": "Menu item added!",
    "vendor.menuItemError": "Failed to add menu item.",
    "vendor.inStock": "in stock",
    "vendor.outOfStock": "Out of Stock",
    "vendor.available": "Available",
    "vendor.unavailable": "Unavailable",
    "vendor.noMenuItems": "No menu items yet",
    "vendor.settings": "Settings",
    "vendor.bankInfoSaved": "Payment info saved",
    "vendor.bankInfoSavedDesc": "Your payment information has been updated.",
    "vendor.bankInfoSaveFailed": "Failed to save payment info.",
    "vendor.saveBankInfo": "Save Payment Info",
    "common.saving": "Saving...",
    "settings.businessImages": "Business Images",
    "settings.businessImagesDesc": "Upload your business logo and photos to attract more customers.",
    "settings.businessLogo": "Business Logo",
    "settings.uploadLogo": "Upload Logo",
    "settings.imageRequirements": "JPEG, PNG, WebP or GIF. Max 5MB.",
    "settings.businessPhotos": "Business Photos",
    "settings.addPhoto": "Add Photo",
    "settings.galleryDesc": "Add photos of your food, restaurant, or services to build trust.",
    "settings.logoSaved": "Logo saved",
    "settings.gallerySaved": "Photos saved",
    "settings.uploadFailed": "Failed to upload image.",
    "settings.paymentInfo": "Payment & Booking Information",
    "settings.paymentInfoDesc": "Set your booking fee and bank details to receive payments.",
    "settings.paymentInfoSaved": "Payment info saved",
    "settings.paymentInfoSavedDesc": "Your payment information has been updated.",
    "settings.paymentInfoFailed": "Failed to save payment info.",
    "settings.bookingFeeLabel": "Booking Fee",
    "settings.bookingFeeDesc": "This fee is charged to customers when they reserve a date. Set to 0 for no booking fee.",
    "booking.platformFee": "Platform Fee",
    "booking.servicePrice": "Service",
    "booking.totalPaid": "Total Paid",
    "provider.bookingUpdated": "Booking updated!",
    "provider.bookingUpdateFailed": "Failed to update booking.",
    "provider.filterAll": "All",
    "provider.filterToday": "Today",
    "provider.filterWeek": "This Week",
    "provider.filterMonth": "This Month",
    "admin.financialReport": "Financial Report",
    "admin.weeklyFinancialReport": "Financial Report",
    "admin.financialReportDesc": "Revenue breakdown by business for payouts to partners.",
    "admin.currentWeek": "Current Week",
    "admin.presetToday": "Today",
    "admin.presetWeek": "This Week",
    "admin.presetMonth": "This Month",
    "admin.presetCustom": "Custom",
    "admin.to": "to",
    "admin.filterBusiness": "Filter by Business",
    "admin.allBusinesses": "All Businesses",
    "admin.weeklyOrders": "Orders",
    "admin.weeklyBookings": "Bookings",
    "admin.platformRevenue": "Platform Revenue (8%)",
    "admin.totalPayouts": "Total Payouts Due",
    "admin.restaurantPayouts": "Restaurant Payouts",
    "admin.providerPayouts": "Service Provider Payouts",
    "admin.ordersThisWeek": "orders this week",
    "admin.ordersPeriod": "orders in period",
    "admin.bookingsThisWeek": "bookings this week",
    "admin.bookingsPeriod": "bookings in period",
    "admin.grossRevenue": "Gross Revenue",
    "admin.totalCollected": "Total Collected",
    "admin.platformFee8": "Platform Fee (8%)",
    "admin.netPayout": "Net Payout",
    "admin.day": "Day",
    "admin.date": "Date",
    "admin.colOrders": "Orders",
    "admin.gross": "Gross",
    "admin.fee": "Fee (8%)",
    "admin.colPayout": "Payout",
    "admin.colBookings": "Bookings",
    "admin.colServices": "Services",
    "admin.bookingFees": "Booking Fees",
    "admin.weekTotal": "Week Total",
    "admin.periodTotal": "Total",
    "admin.noTransactionsWeek": "No transactions this week.",
    "admin.noTransactionsPeriod": "No transactions in this period.",
    "vendor.filterByStatus": "Filter by Status",
    "vendor.allStatuses": "All Statuses",
    "vendor.dateRange": "Date Range",
    "vendor.today": "Today",
    "vendor.thisWeek": "This Week",
    "vendor.thisMonth": "This Month",
    "vendor.allTime": "All Time",
    "vendor.revenue": "Revenue",
    "vendor.totalOrders": "Total Orders",
    "vendor.avgOrder": "Avg. Order",
    "vendor.filteredOrders": "Orders",
    "vendor.noFilteredOrders": "No orders match the selected filters",

    "checkout.title": "Checkout",
    "checkout.deliveryAddress": "Delivery Address",
    "checkout.fullAddress": "Full Address",
    "checkout.addressPlaceholder": "Enter your delivery address...",
    "checkout.deliveryInstructions": "Delivery Instructions (Optional)",
    "checkout.instructionsPlaceholder": "Apartment number, gate code, etc...",
    "checkout.addTip": "Add a Tip",
    "checkout.noTip": "No tip",
    "checkout.paymentMethod": "Payment Method",
    "checkout.loadingPayment": "Loading payment...",
    "checkout.enterAddress": "Please enter your delivery address above to proceed with payment.",
    "checkout.preparingPayment": "Preparing payment form...",
    "checkout.loadingPaymentForm": "Loading payment form...",
    "checkout.processingPayment": "Processing Payment...",
    "checkout.securePayment": "Payments are securely processed by Stripe",
    "checkout.orderSummary": "Order Summary",
    "checkout.tip": "Tip",
    "checkout.payWithStripe": "Pay with Stripe",
    "checkout.processing": "Processing...",
    "checkout.notes": "Special Instructions",
    "checkout.paymentFailed": "Payment Failed",
    "checkout.paymentFailedDesc": "Your payment could not be processed. Please try again.",
    "checkout.orderConfirmed": "Order Confirmed!",
    "checkout.orderConfirmedDesc": "Thank you for your order! Your food is being prepared and will be on its way soon.",
    "checkout.orderId": "Order ID",
    "checkout.viewOrder": "View Order",
    "checkout.continueShopping": "Continue Shopping",
    "checkout.processingOrder": "Processing your order...",
    "checkout.confirmingPayment": "Please wait while we confirm your payment.",
    "checkout.somethingWrong": "Something went wrong",
    "checkout.orderError": "We couldn't process your order. Please contact support if you were charged.",
    "checkout.returnToCart": "Return to Cart",
    "checkout.initError": "Failed to initialize payment. Please try again.",
    "checkout.orderCreateError": "Payment was successful but order creation failed. Please contact support.",
    "checkout.paymentLoadError": "Could not load payment system. Please try again.",
    "checkout.retryPayment": "Try Again",
    "checkout.paymentInitError": "Could not set up payment. Please try again.",

    "notifications.title": "Notifications",
    "notifications.noNotifications": "No notifications",
    "notifications.noNotificationsDesc": "You're all caught up! Check back later for updates.",

    "notFound.title": "Page Not Found",
    "notFound.desc": "The page you're looking for doesn't exist or has been moved.",
    "notFound.goHome": "Go Home",

    "admin.title": "Admin Dashboard",
    "admin.users": "Users",
    "admin.restaurants": "Restaurants",
    "admin.services": "Services",
    "admin.orders": "Orders",
    "admin.events": "Events",
    "admin.businesses": "Businesses",
    "admin.announcements": "Announcements",

    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.tryAgain": "Try again",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.close": "Close",

    "pendingApproval.title": "Registration Under Review",
    "pendingApproval.desc": "Your registration as a",
    "pendingApproval.descEnd": "is currently being reviewed by our team.",
    "pendingApproval.wait": "You will be notified once your account has been approved. This usually takes 1-2 business days.",
    "pendingApproval.vendorRole": "Restaurant / Food Vendor",
    "pendingApproval.providerRole": "Service Provider",
    "pendingApproval.statusLabel": "Status",
    "pendingApproval.statusPending": "Pending Review",
    "pendingApproval.statusRejected": "Rejected",
    "pendingApproval.role": "Role",
    "pendingApproval.logout": "Sign Out",
    "pendingApproval.rejectedTitle": "Registration Not Approved",
    "pendingApproval.rejectedDesc": "Unfortunately, your registration as a",
    "pendingApproval.rejectedDescEnd": "was not approved at this time.",
    "pendingApproval.rejectedContact": "Please contact support if you believe this was a mistake.",

    "onboarding.pendingToast": "Registration Submitted",
    "onboarding.pendingToastDesc": "Your registration is pending admin approval. You'll be notified once approved.",

    "authDialog.title": "Welcome to BrazaDash",
    "authDialog.description": "Sign in to order food, book services, and connect with the Brazilian community in California.",
    "authDialog.rolePrompt": "How would you like to use BrazaDash?",
    "authDialog.role.customer": "Customer",
    "authDialog.role.customerDesc": "Order food, book services, and explore the community",
    "authDialog.role.vendor": "Restaurant Owner",
    "authDialog.role.vendorDesc": "List your restaurant and manage orders",
    "authDialog.role.provider": "Service Provider",
    "authDialog.role.providerDesc": "Offer your services and manage bookings",
    "authDialog.continue": "Continue",
    "authDialog.login": "Log In",
    "authDialog.register": "Create Account",
    "authDialog.secure": "Secured by Replit Authentication",

    "onboarding.einNumber": "EIN Number (Tax ID)",
    "onboarding.einNumberDesc": "Your Employer Identification Number for tax purposes (optional).",
    "onboarding.bankInfoTitle": "Payment Information",
    "onboarding.bankInfoDesc": "Provide your bank details so you can receive payments from orders and bookings.",
    "onboarding.bankName": "Bank Name",
    "onboarding.bankNamePlaceholder": "e.g. Bank of America, Chase",
    "onboarding.routingNumber": "Routing Number",
    "onboarding.routingNumberPlaceholder": "9-digit routing number",
    "onboarding.bankAccountNumber": "Account Number",
    "onboarding.bankAccountPlaceholder": "Bank account number",
    "onboarding.zelleInfo": "Zelle (Email or Phone)",
    "onboarding.zelleInfoPlaceholder": "Zelle email or phone number",
    "onboarding.venmoInfo": "Venmo Username",
    "onboarding.venmoInfoPlaceholder": "@username",
    "onboarding.businessImage": "Business Image",
    "onboarding.removeImage": "Remove",
    "onboarding.uploadBusinessImage": "Click to upload business image",
    "onboarding.imageFormats": "JPEG, PNG, WebP, GIF (max 5MB)",
    "onboarding.imageTooLarge": "Image must be less than 5MB",
    "onboarding.uploadFailed": "Failed to upload image",
    "onboarding.uploading": "Uploading...",

    "booking.book": "Book",
    "booking.requestBooking": "Request Booking",
    "booking.selectDateTime": "Select your preferred date and time for the service",
    "booking.date": "Date",
    "booking.selectDate": "Select date",
    "booking.time": "Time",
    "booking.address": "Address",
    "booking.addressPlaceholder": "Service location address",
    "booking.notes": "Notes (optional)",
    "booking.notesPlaceholder": "Any special requests or details...",
    "booking.paymentSummary": "Payment Summary",
    "booking.bookingFee": "Booking Fee",
    "booking.total": "Total",
    "booking.payAndBook": "Pay & Book",
    "booking.processing": "Processing...",
    "booking.loginToBook": "Login to Book",
    "booking.error": "Error",
    "booking.checkoutFailed": "Failed to create checkout session.",
    "booking.paymentSuccess": "Payment Successful!",
    "booking.bookingCreated": "Your booking has been created. The provider will respond soon.",
    "booking.paymentCompleteFailed": "Failed to complete booking payment.",

    "checkout.platformFee": "Platform Fee",

    "terminal.title": "Stripe Terminal (In-Person Payments)",
    "terminal.description": "Accept in-person card payments using a Stripe Terminal card reader at your restaurant.",
    "terminal.enableTerminal": "Enable In-Person Payments",
    "terminal.enableDesc": "Turn on Stripe Terminal to accept card payments in person.",
    "terminal.settingsUpdated": "Terminal settings updated",
    "terminal.settingsUpdateFailed": "Failed to update terminal settings",
    "terminal.location": "Terminal Location",
    "terminal.locationId": "Location ID",
    "terminal.noLocation": "No terminal location set up yet. Create one to connect card readers.",
    "terminal.setupLocation": "Set Up Location",
    "terminal.locationCreated": "Terminal location created successfully",
    "terminal.locationCreateFailed": "Failed to create terminal location",
    "terminal.zipCode": "ZIP Code",
    "terminal.zipRequired": "Please enter a valid 5-digit ZIP code for your restaurant location.",
    "terminal.connectedReaders": "Connected Card Readers",
    "terminal.readersDesc": "Card readers registered at your terminal location.",
    "terminal.noReaders": "No card readers found",
    "terminal.noReadersHint": "Register a reader through the Stripe Dashboard or use the mobile app to discover nearby readers.",
    "terminal.createCharge": "Create In-Person Charge",
    "terminal.createChargeDesc": "Create a payment intent for an in-person card payment. Use the mobile app to collect the payment.",
    "terminal.amount": "Amount (USD)",
    "terminal.chargeDescription": "Description",
    "terminal.chargeDescPlaceholder": "e.g. Table 5 order",
    "terminal.createPaymentIntent": "Create Payment Intent",
    "terminal.chargeCreated": "Payment intent created",
    "terminal.paymentIntentId": "Payment Intent ID",
    "terminal.chargeCreateFailed": "Failed to create payment intent",
    "terminal.tipping": "On-Reader Tipping",
    "terminal.tippingDesc": "Show tip options (15%, 20%, 25%) on the card reader screen before collecting payment.",
    "terminal.tippingEnabled": "Tipping enabled",
    "terminal.tippingDisabled": "Tipping disabled",
    "terminal.tipIncluded": "Tip included",
    "terminal.captureFailed": "Capture Failed",
    "terminal.captureFailedDesc": "The payment was authorized but failed to capture. Please try again.",
    "terminal.retryCapture": "Retry Capture",
    "terminal.paymentFailed": "Payment Failed",
    "terminal.cardDeclined": "Card was declined or removed. Please try again.",
    "terminal.customerEmail": "Customer Email (Optional)",
    "terminal.customerEmailPlaceholder": "customer@email.com (optional)",
    "terminal.customerEmailHint": "Enter customer email to send a receipt after payment",
    "common.dismiss": "Dismiss",
    "common.refresh": "Refresh",
  },
  pt: {
    "nav.home": "Inicio",
    "nav.food": "Comida",
    "nav.services": "Servicos",
    "nav.community": "Comunidade",
    "nav.myOrders": "Meus Pedidos",
    "nav.myRestaurant": "Meu Restaurante",
    "nav.myServices": "Meus Servicos",
    "nav.getStarted": "Comecar",
    "nav.logout": "Sair",
    "nav.switchAccount": "Trocar Conta",
    "nav.restaurantPortal": "Portal do Restaurante",
    "nav.serviceProviderPortal": "Portal de Servicos",
    "nav.myBookings": "Minhas Reservas",
    "nav.adminDashboard": "Painel Admin",
    "nav.restaurantVendor": "Restaurante",
    "nav.serviceProvider": "Prestador de Servicos",
    "nav.customer": "Cliente",

    "landing.aboutTitle": "Sobre o BrazaDash",
    "landing.aboutDesc": "O BrazaDash.com e uma plataforma criada para conectar, apoiar e impulsionar a comunidade brasileira, reunindo empresas, restaurantes, prestadores de servicos e clientes em um unico espaco digital centralizado.",
    "landing.aboutMissionTitle": "Nossa missao e simples:",
    "landing.aboutMission": "Fortalecer nossa comunidade tornando produtos, servicos, cultura e eventos brasileiros mais acessiveis e visiveis para todos.",
    "landing.aboutClosing": "O BrazaDash e mais do que um marketplace — e um ponto de encontro comunitario onde as pessoas podem descobrir, interagir e apoiar o empreendedorismo e a cultura brasileira.",
    "landing.exploreFood": "Explorar Comida",
    "landing.exploreServices": "Explorar Servicos",
    "landing.exploreCommunity": "Explorar Comunidade",

    "landing.badge": "Atendendo a California",
    "landing.heroTitle1": "Sabor brasileiro",
    "landing.heroTitle2": "na sua porta",
    "landing.heroDesc": "Descubra a autentica culinaria brasileira dos seus restaurantes favoritos. De feijoada a pao de queijo, experimente o sabor do Brasil aqui na California.",
    "landing.orderNow": "Pedir Agora",
    "landing.learnMore": "Saiba Mais",
    "landing.securePayments": "Pagamentos seguros",
    "landing.fastDelivery": "Entrega rapida",
    "landing.rating": "4.9 Avaliacao",
    "landing.happyCustomers": "10k+ clientes satisfeitos",
    "landing.whyChoose": "Por que escolher",
    "landing.whyChooseDesc": "Trazemos o autentico sabor do Brasil ate a sua porta com cuidado e qualidade.",
    "landing.authenticCuisine": "Culinaria Brasileira Autentica",
    "landing.authenticCuisineDesc": "Da tradicional feijoada as coxinhas de rua, experimente sabores genuinos brasileiros preparados por cozinheiros apaixonados.",
    "landing.localCommunity": "Comunidade Local",
    "landing.localCommunityDesc": "Conecte-se com restaurantes e cozinheiros brasileiros no seu bairro. Apoie sua comunidade local.",
    "landing.fastDeliveryTitle": "Entrega Rapida",
    "landing.fastDeliveryDesc": "Receba seus pratos brasileiros favoritos quentes e frescos. Acompanhe seu pedido em tempo real da cozinha ate a porta.",
    "landing.verifiedReviews": "Avaliacoes Verificadas",
    "landing.verifiedReviewsDesc": "Tome decisoes informadas com avaliacoes honestas de clientes reais. Cada nota e de um pedido verificado.",
    "landing.securePaymentsTitle": "Pagamentos Seguros",
    "landing.securePaymentsDesc": "Suas transacoes sao protegidas com criptografia padrao da industria. Pague com confianca usando seu metodo preferido.",
    "landing.madeWithLove": "Feito com Amor",
    "landing.madeWithLoveDesc": "Cada prato e preparado com o mesmo amor e cuidado de uma refeicao caseira brasileira. Saudade nunca teve sabor tao bom.",
    "landing.readyToTaste": "Pronto para experimentar o Brasil?",
    "landing.readyToTasteDesc": "Junte-se a milhares de brasileiros na California aproveitando comida autentica no conforto de suas casas.",
    "landing.getStartedFree": "Comecar - E Gratis",
    "landing.footer": "\u00a9 2024 BrazaDash. Feito com amor para a comunidade brasileira.",

    "onboarding.welcome": "Bem-vindo ao BrazaDash!",
    "onboarding.subtitle": "Como voce gostaria de usar a plataforma?",
    "onboarding.subtitlePt": "",
    "onboarding.customer": "Cliente",
    "onboarding.customerSub": "Comprar",
    "onboarding.customerDesc": "Navegue pelos restaurantes, peca comida, reserve servicos e explore a comunidade.",
    "onboarding.vendor": "Restaurante / Vendedor de Comida",
    "onboarding.vendorSub": "Vender Comida",
    "onboarding.vendorDesc": "Gerencie seu restaurante, crie cardapios e processe pedidos de comida dos clientes.",
    "onboarding.provider": "Prestador de Servicos",
    "onboarding.providerSub": "Oferecer Servicos",
    "onboarding.providerDesc": "Liste seus servicos profissionais, gerencie reservas e amplie sua base de clientes.",
    "onboarding.continue": "Continuar",
    "onboarding.next": "Proximo",
    "onboarding.back": "Voltar",
    "onboarding.submit": "Enviar Registro",
    "onboarding.submitting": "Enviando...",
    "onboarding.settingUp": "Configurando sua conta...",
    "onboarding.changeRole": "Voce pode entrar em contato com o suporte depois se precisar mudar sua funcao.",
    "onboarding.welcomeToast": "Bem-vindo ao BrazaDash!",
    "onboarding.welcomeToastDesc": "Sua conta esta pronta. Vamos comecar!",
    "onboarding.error": "Algo deu errado",
    "onboarding.errorDesc": "Por favor, tente novamente.",
    "onboarding.step1": "Escolha Sua Funcao",
    "onboarding.step2": "Informacoes do Negocio",
    "onboarding.vendorInfoTitle": "Conte-nos sobre seu restaurante",
    "onboarding.vendorInfoDesc": "Estas informacoes serao analisadas pela nossa equipe antes de seu restaurante ficar ativo.",
    "onboarding.providerInfoTitle": "Conte-nos sobre seus servicos",
    "onboarding.providerInfoDesc": "Estas informacoes serao analisadas pela nossa equipe antes de seu perfil ficar ativo.",
    "onboarding.restaurantName": "Nome do Restaurante",
    "onboarding.restaurantNamePlaceholder": "ex. Sabor do Brasil",
    "onboarding.businessDescription": "Descricao",
    "onboarding.businessDescriptionPlaceholder": "Descreva seu restaurante e o que o torna especial...",
    "onboarding.cuisine": "Tipo de Culinaria",
    "onboarding.cuisinePlaceholder": "ex. Brasileira, Churrasco, Padaria",
    "onboarding.city": "Cidade",
    "onboarding.cityPlaceholder": "ex. San Francisco",
    "onboarding.address": "Endereco",
    "onboarding.addressPlaceholder": "Endereco completo",
    "onboarding.phone": "Telefone",
    "onboarding.phonePlaceholder": "(555) 123-4567",
    "onboarding.businessName": "Nome do Negocio",
    "onboarding.businessNamePlaceholder": "ex. Limpeza da Maria",
    "onboarding.providerDescriptionPlaceholder": "Descreva os servicos que voce oferece...",
    "onboarding.category": "Categoria do Servico",
    "onboarding.categoryPlaceholder": "Selecione uma categoria",
    "onboarding.email": "Email Comercial",
    "onboarding.emailPlaceholder": "contato@seunegocio.com",
    "onboarding.categoryCleaning": "Limpeza",
    "onboarding.categoryBeauty": "Beleza",
    "onboarding.categoryLegal": "Juridico",
    "onboarding.categoryFitness": "Fitness",
    "onboarding.categoryAuto": "Automotivo",
    "onboarding.categoryConstruction": "Construcao",
    "onboarding.categoryOther": "Outro",
    "onboarding.required": "Obrigatorio",

    "home.badge": "Comunidade Brasileira na California",
    "home.greeting": "Ola",
    "home.welcomeTo": "Bem-vindo ao BrazaDash",
    "home.heroDesc": "Sua conexao com a comunidade brasileira na California. Descubra restaurantes autenticos, encontre servicos de confianca e conecte-se com a nossa comunidade.",
    "home.orderFood": "Pedir Comida",
    "home.findServices": "Encontrar Servicos",
    "home.community": "Comunidade",
    "home.popularServices": "Servicos Populares",
    "home.popularServicesDesc": "Servicos populares da nossa comunidade brasileira",
    "home.viewAll": "Ver Todos",
    "home.featuredProviders": "Provedores em Destaque",
    "home.featuredRestaurants": "Restaurantes em Destaque",
    "home.featuredRestaurantsDesc": "Descubra a melhor comida brasileira na sua regiao",
    "home.noRestaurants": "Nenhum restaurante ainda",
    "home.noRestaurantsDesc": "Seja o primeiro a adicionar seu restaurante no BrazaDash!",
    "home.becomeVendor": "Seja um Vendedor",
    "home.testimonialsBadge": "Depoimentos da Comunidade",
    "home.testimonialsTitle": "O Que Nossa Comunidade Diz",
    "home.testimonialsDesc": "O que nossa comunidade diz sobre o BrazaDash",
    "home.recentReviews": "Avaliacoes Recentes",
    "home.recentReviewsDesc": "Ultimas avaliacoes da comunidade",
    "home.communityHub": "Hub da Comunidade",
    "home.upcomingEvents": "Proximos Eventos",
    "home.viewAllEvents": "Ver todos os eventos",
    "home.noEvents": "Nenhum evento proximo",
    "home.businessDirectory": "Diretorio de Empresas",
    "home.viewAllBusinesses": "Ver todas as empresas",
    "home.noBusinesses": "Nenhuma empresa listada ainda",
    "home.announcements": "Anuncios",
    "home.noAnnouncements": "Nenhum anuncio",
    "home.open": "Aberto",
    "home.closed": "Fechado",
    "home.delivery": "entrega",
    "home.verified": "Verificado",
    "home.food": "Comida",
    "home.service": "Servico",

    "home.cleaning": "Limpeza",
    "home.beauty": "Beleza",
    "home.legal": "Legal",
    "home.fitness": "Fitness",
    "home.auto": "Auto",
    "home.construction": "Construcao",

    "restaurants.title": "Restaurantes Brasileiros",
    "restaurants.subtitle": "Descubra comida brasileira autentica na sua regiao",
    "restaurants.search": "Buscar restaurantes...",
    "restaurants.all": "Todos",
    "restaurants.noResults": "Nenhum restaurante encontrado",
    "restaurants.noResultsDesc": "Tente ajustar sua busca ou filtros.",
    "restaurants.open": "Aberto",
    "restaurants.closed": "Fechado",

    "services.title": "Servicos Brasileiros",
    "services.subtitle": "Encontre prestadores de servicos brasileiros de confianca na sua regiao",
    "services.search": "Buscar servicos...",
    "services.allCategories": "Todas as Categorias",
    "services.noResults": "Nenhum prestador de servicos encontrado",
    "services.noResultsDesc": "Tente ajustar sua busca ou filtros.",
    "services.startingAt": "A partir de",
    "services.viewProfile": "Ver Perfil",
    "services.verified": "Verificado",
    "services.reviews": "avaliacoes",

    "community.title": "Hub da Comunidade",
    "community.subtitle": "Conecte-se com a comunidade brasileira na California",
    "community.events": "Eventos",
    "community.businesses": "Empresas",
    "community.announcements": "Anuncios",
    "community.featuredEvents": "Eventos em Destaque",
    "community.upcomingEvents": "Proximos Eventos",
    "community.viewAllEvents": "Ver Todos os Eventos",
    "community.noEvents": "Nenhum evento encontrado",
    "community.noEventsDesc": "Volte em breve para eventos da comunidade!",
    "community.rsvp": "Confirmar Presenca",
    "community.attending": "confirmados",
    "community.free": "Gratis",
    "community.yellowPages": "Paginas Amarelas",
    "community.yellowPagesDesc": "Quartos, casas, apartamentos, carros e mais",
    "community.viewYellowPages": "Ver Anuncios",
    "community.browseYellowPages": "Ver Paginas Amarelas",
    "community.addEvent": "Adicionar Evento",
    "community.latestAnnouncements": "Ultimos Anuncios",

    "yp.title": "Paginas Amarelas",
    "yp.subtitle": "Encontre quartos, casas, apartamentos, carros e mais da comunidade brasileira",
    "yp.addListing": "Adicionar Anuncio",
    "yp.newListing": "Novo Anuncio",
    "yp.listingTitle": "Titulo",
    "yp.titlePlaceholder": "ex. Quarto para alugar em Los Angeles",
    "yp.category": "Categoria",
    "yp.description": "Descricao",
    "yp.descriptionPlaceholder": "Descreva o que voce esta oferecendo...",
    "yp.price": "Preco",
    "yp.city": "Cidade",
    "yp.address": "Endereco",
    "yp.addressPlaceholder": "Endereco (opcional)",
    "yp.contactName": "Nome de Contato",
    "yp.contactPhone": "Telefone",
    "yp.contactEmail": "Email",
    "yp.allCities": "Todas as Cidades",
    "yp.all": "Todos",
    "yp.searchPlaceholder": "Buscar anuncios...",
    "yp.noListings": "Nenhum anuncio encontrado",
    "yp.noListingsFiltered": "Nenhum anuncio corresponde aos seus filtros. Tente ajustar sua busca.",
    "yp.noListingsYet": "Nenhum anuncio ainda. Seja o primeiro a publicar!",
    "yp.submit": "Enviar Anuncio",
    "yp.submitting": "Enviando...",
    "yp.submitSuccess": "Anuncio Enviado",
    "yp.submitSuccessDesc": "Seu anuncio foi enviado e esta aguardando aprovacao do administrador.",
    "yp.submitError": "Erro",
    "yp.submitErrorDesc": "Falha ao enviar anuncio. Tente novamente.",
    "yp.approvalNotice": "Todos os anuncios requerem aprovacao do administrador antes de ficarem visiveis.",
    "yp.listingImage": "Foto",
    "yp.imageRecommendation": "Tamanho recomendado: 1200 x 630 pixels (paisagem). As imagens serao redimensionadas para manter o layout uniforme.",
    "yp.uploadImage": "Clique para enviar foto",
    "yp.uploadingImage": "Enviando...",
    "yp.imageUploaded": "Foto Enviada",
    "yp.imageUploadedDesc": "Sua foto foi enviada com sucesso.",
    "yp.imageUploadError": "Falha ao enviar foto. Tente novamente.",

    "events.addEvent": "Adicionar Evento",
    "events.newEvent": "Novo Evento",
    "events.eventTitle": "Titulo do Evento",
    "events.eventTitlePlaceholder": "ex. Noite de Churrasco Brasileiro",
    "events.eventCategory": "Categoria",
    "events.eventDescription": "Descricao",
    "events.eventDescriptionPlaceholder": "Descreva seu evento...",
    "events.eventDate": "Data do Evento",
    "events.startTime": "Hora de Inicio",
    "events.endTime": "Hora de Termino",
    "events.venue": "Local",
    "events.venuePlaceholder": "ex. Parque Central",
    "events.eventCity": "Cidade",
    "events.isFree": "Evento Gratuito",
    "events.ticketPrice": "Preco do Ingresso",
    "events.ticketUrl": "URL do Ingresso",
    "events.submitEvent": "Enviar Evento",
    "events.submittingEvent": "Enviando...",
    "events.submitEventSuccess": "Evento Enviado",
    "events.submitEventSuccessDesc": "Seu evento foi enviado e esta aguardando aprovacao do administrador.",
    "events.submitEventError": "Erro",
    "events.submitEventErrorDesc": "Falha ao enviar evento. Tente novamente.",
    "events.approvalNotice": "Todos os eventos requerem aprovacao do administrador antes de ficarem visiveis.",
    "events.eventImage": "Imagem do Evento",
    "events.imageRecommendation": "Tamanho recomendado: 1200 x 630 pixels (paisagem). As imagens serao redimensionadas para manter o layout uniforme.",
    "events.uploadImage": "Clique para enviar imagem",
    "events.uploadingImage": "Enviando...",
    "events.imageUploaded": "Imagem Enviada",
    "events.imageUploadedDesc": "Sua imagem foi enviada com sucesso.",
    "events.imageUploadError": "Falha ao enviar imagem. Tente novamente.",

    "community.noAnnouncements": "Nenhum anuncio",
    "community.noAnnouncementsDesc": "Volte em breve para anuncios da comunidade!",

    "cart.title": "Seu Carrinho",
    "cart.empty": "Seu carrinho esta vazio",
    "cart.emptyDesc": "Parece que voce ainda nao adicionou nenhum item. Explore nossos deliciosos restaurantes brasileiros!",
    "cart.browseRestaurants": "Ver Restaurantes",
    "cart.orderFrom": "Pedido de",
    "cart.items": "Itens",
    "cart.clearCart": "Limpar Carrinho",
    "cart.subtotal": "Subtotal",
    "cart.deliveryFee": "Taxa de Entrega",
    "cart.total": "Total",
    "cart.proceedToCheckout": "Ir para Pagamento",
    "cart.remove": "Remover",

    "orders.title": "Meus Pedidos",
    "orders.subtitle": "Acompanhe seus pedidos de comida e status de entrega",
    "orders.noOrders": "Nenhum pedido ainda",
    "orders.noOrdersDesc": "Comece explorando nossos restaurantes e faca seu primeiro pedido!",
    "orders.browseRestaurants": "Ver Restaurantes",
    "orders.orderNumber": "Pedido",
    "orders.items": "itens",
    "orders.viewDetails": "Ver Detalhes",
    "orders.pending": "Pendente",
    "orders.confirmed": "Confirmado",
    "orders.preparing": "Preparando",
    "orders.ready": "Pronto",
    "orders.outForDelivery": "Saiu para Entrega",
    "orders.delivered": "Entregue",
    "orders.cancelled": "Cancelado",

    "vendor.dashboard": "Painel do Restaurante",
    "vendor.createRestaurant": "Crie Seu Restaurante",
    "vendor.restaurantName": "Nome do Restaurante",
    "vendor.description": "Descricao",
    "vendor.cuisine": "Tipo de Culinaria",
    "vendor.address": "Endereco",
    "vendor.phone": "Telefone",
    "vendor.deliveryFee": "Taxa de Entrega",
    "vendor.create": "Criar Restaurante",
    "vendor.creating": "Criando...",
    "vendor.orders": "Pedidos",
    "vendor.menu": "Cardapio",
    "vendor.newOrders": "Novos Pedidos",
    "vendor.activeOrders": "Pedidos Ativos",
    "vendor.completed": "Concluidos",
    "vendor.noOrders": "Nenhum pedido ainda",
    "vendor.accept": "Aceitar Pedido",
    "vendor.decline": "Recusar",
    "vendor.startPreparing": "Comecar a Preparar",
    "vendor.readyForPickup": "Pronto para Retirada",
    "vendor.outForDelivery": "Saiu para Entrega",
    "vendor.markDelivered": "Marcar como Entregue",
    "vendor.addMenuItem": "Adicionar Item",
    "vendor.itemName": "Nome do Item",
    "vendor.price": "Preco",
    "vendor.category": "Categoria",
    "vendor.save": "Salvar",
    "vendor.pending": "Pendente",
    "vendor.active": "Ativo",
    "vendor.rating": "Avaliacao",
    "vendor.menuItems": "Itens do Cardapio",
    "vendor.restaurantOpen": "Restaurante esta aberto",
    "vendor.restaurantClosed": "Restaurante esta fechado",
    "vendor.newOrder": "Novo Pedido",
    "vendor.orderConfirmed": "Confirmado",
    "vendor.orderPreparing": "Preparando",
    "vendor.orderReady": "Pronto para Retirada",
    "vendor.orderOutForDelivery": "Saiu para Entrega",
    "vendor.orderDelivered": "Entregue",
    "vendor.orderCancelled": "Cancelado",
    "vendor.quantity": "Disponibilidade (Quantidade)",
    "vendor.quantityPlaceholder": "Deixe vazio para ilimitado",
    "vendor.quantityHint": "Defina o numero de porcoes disponiveis. Deixe vazio para ilimitado.",
    "vendor.itemImage": "Imagem do Item",
    "vendor.uploadImage": "Clique para enviar uma imagem",
    "vendor.uploadImageHint": "JPEG, PNG, WebP ou GIF (max 5MB)",
    "vendor.imageUploaded": "Imagem enviada com sucesso",
    "vendor.imageUploadError": "Falha ao enviar imagem",
    "vendor.removeImage": "Remover",
    "vendor.menuItemAdded": "Item adicionado ao cardapio!",
    "vendor.menuItemError": "Falha ao adicionar item.",
    "vendor.inStock": "em estoque",
    "vendor.outOfStock": "Esgotado",
    "vendor.available": "Disponivel",
    "vendor.unavailable": "Indisponivel",
    "vendor.noMenuItems": "Nenhum item no cardapio ainda",
    "vendor.settings": "Configuracoes",
    "vendor.bankInfoSaved": "Informacoes de pagamento salvas",
    "vendor.bankInfoSavedDesc": "Suas informacoes de pagamento foram atualizadas.",
    "vendor.bankInfoSaveFailed": "Falha ao salvar informacoes de pagamento.",
    "vendor.saveBankInfo": "Salvar Informacoes de Pagamento",
    "common.saving": "Salvando...",
    "settings.businessImages": "Imagens do Negocio",
    "settings.businessImagesDesc": "Envie o logotipo e fotos do seu negocio para atrair mais clientes.",
    "settings.businessLogo": "Logotipo do Negocio",
    "settings.uploadLogo": "Enviar Logotipo",
    "settings.imageRequirements": "JPEG, PNG, WebP ou GIF. Max 5MB.",
    "settings.businessPhotos": "Fotos do Negocio",
    "settings.addPhoto": "Adicionar Foto",
    "settings.galleryDesc": "Adicione fotos da sua comida, restaurante ou servicos para construir confianca.",
    "settings.logoSaved": "Logotipo salvo",
    "settings.gallerySaved": "Fotos salvas",
    "settings.uploadFailed": "Falha ao enviar imagem.",
    "settings.paymentInfo": "Informacoes de Pagamento e Reserva",
    "settings.paymentInfoDesc": "Defina sua taxa de reserva e dados bancarios para receber pagamentos.",
    "settings.paymentInfoSaved": "Informacoes de pagamento salvas",
    "settings.paymentInfoSavedDesc": "Suas informacoes de pagamento foram atualizadas.",
    "settings.paymentInfoFailed": "Falha ao salvar informacoes de pagamento.",
    "settings.bookingFeeLabel": "Taxa de Reserva",
    "settings.bookingFeeDesc": "Esta taxa e cobrada dos clientes quando reservam uma data. Defina como 0 para nenhuma taxa.",
    "booking.platformFee": "Taxa da Plataforma",
    "booking.servicePrice": "Servico",
    "booking.totalPaid": "Total Pago",
    "provider.bookingUpdated": "Reserva atualizada!",
    "provider.bookingUpdateFailed": "Falha ao atualizar reserva.",
    "provider.filterAll": "Todos",
    "provider.filterToday": "Hoje",
    "provider.filterWeek": "Esta Semana",
    "provider.filterMonth": "Este Mes",
    "admin.financialReport": "Relatorio Financeiro",
    "admin.weeklyFinancialReport": "Relatorio Financeiro",
    "admin.financialReportDesc": "Detalhamento de receita por negocio para pagamentos aos parceiros.",
    "admin.currentWeek": "Semana Atual",
    "admin.presetToday": "Hoje",
    "admin.presetWeek": "Esta Semana",
    "admin.presetMonth": "Este Mes",
    "admin.presetCustom": "Personalizado",
    "admin.to": "ate",
    "admin.filterBusiness": "Filtrar por Negocio",
    "admin.allBusinesses": "Todos os Negocios",
    "admin.weeklyOrders": "Pedidos",
    "admin.weeklyBookings": "Reservas",
    "admin.platformRevenue": "Receita da Plataforma (8%)",
    "admin.totalPayouts": "Total a Pagar",
    "admin.restaurantPayouts": "Pagamentos a Restaurantes",
    "admin.providerPayouts": "Pagamentos a Prestadores de Servico",
    "admin.ordersThisWeek": "pedidos esta semana",
    "admin.ordersPeriod": "pedidos no periodo",
    "admin.bookingsThisWeek": "reservas esta semana",
    "admin.bookingsPeriod": "reservas no periodo",
    "admin.grossRevenue": "Receita Bruta",
    "admin.totalCollected": "Total Recebido",
    "admin.platformFee8": "Taxa da Plataforma (8%)",
    "admin.netPayout": "Pagamento Liquido",
    "admin.day": "Dia",
    "admin.date": "Data",
    "admin.colOrders": "Pedidos",
    "admin.gross": "Bruto",
    "admin.fee": "Taxa (8%)",
    "admin.colPayout": "Pagamento",
    "admin.colBookings": "Reservas",
    "admin.colServices": "Servicos",
    "admin.bookingFees": "Taxas de Reserva",
    "admin.weekTotal": "Total da Semana",
    "admin.periodTotal": "Total",
    "admin.noTransactionsWeek": "Nenhuma transacao esta semana.",
    "admin.noTransactionsPeriod": "Nenhuma transacao neste periodo.",
    "vendor.filterByStatus": "Filtrar por Status",
    "vendor.allStatuses": "Todos os Status",
    "vendor.dateRange": "Periodo",
    "vendor.today": "Hoje",
    "vendor.thisWeek": "Esta Semana",
    "vendor.thisMonth": "Este Mes",
    "vendor.allTime": "Todo o Periodo",
    "vendor.revenue": "Receita",
    "vendor.totalOrders": "Total de Pedidos",
    "vendor.avgOrder": "Pedido Medio",
    "vendor.filteredOrders": "Pedidos",
    "vendor.noFilteredOrders": "Nenhum pedido corresponde aos filtros selecionados",

    "checkout.title": "Pagamento",
    "checkout.deliveryAddress": "Endereco de Entrega",
    "checkout.fullAddress": "Endereco Completo",
    "checkout.addressPlaceholder": "Digite seu endereco de entrega...",
    "checkout.deliveryInstructions": "Instrucoes de Entrega (Opcional)",
    "checkout.instructionsPlaceholder": "Numero do apartamento, codigo do portao, etc...",
    "checkout.addTip": "Adicionar Gorjeta",
    "checkout.noTip": "Sem gorjeta",
    "checkout.paymentMethod": "Metodo de Pagamento",
    "checkout.loadingPayment": "Carregando pagamento...",
    "checkout.enterAddress": "Por favor, insira seu endereco de entrega acima para prosseguir com o pagamento.",
    "checkout.preparingPayment": "Preparando formulario de pagamento...",
    "checkout.loadingPaymentForm": "Carregando formulario de pagamento...",
    "checkout.processingPayment": "Processando Pagamento...",
    "checkout.securePayment": "Pagamentos processados com seguranca pelo Stripe",
    "checkout.orderSummary": "Resumo do Pedido",
    "checkout.tip": "Gorjeta",
    "checkout.payWithStripe": "Pagar com Stripe",
    "checkout.processing": "Processando...",
    "checkout.notes": "Instrucoes Especiais",
    "checkout.paymentFailed": "Pagamento Falhou",
    "checkout.paymentFailedDesc": "Seu pagamento nao pôde ser processado. Por favor, tente novamente.",
    "checkout.orderConfirmed": "Pedido Confirmado!",
    "checkout.orderConfirmedDesc": "Obrigado pelo seu pedido! Sua comida esta sendo preparada e logo estara a caminho.",
    "checkout.orderId": "ID do Pedido",
    "checkout.viewOrder": "Ver Pedido",
    "checkout.continueShopping": "Continuar Comprando",
    "checkout.processingOrder": "Processando seu pedido...",
    "checkout.confirmingPayment": "Por favor, aguarde enquanto confirmamos seu pagamento.",
    "checkout.somethingWrong": "Algo deu errado",
    "checkout.orderError": "Nao foi possivel processar seu pedido. Entre em contato com o suporte se voce foi cobrado.",
    "checkout.returnToCart": "Voltar ao Carrinho",
    "checkout.initError": "Falha ao inicializar pagamento. Por favor, tente novamente.",
    "checkout.orderCreateError": "Pagamento realizado com sucesso, mas a criacao do pedido falhou. Entre em contato com o suporte.",
    "checkout.paymentLoadError": "Nao foi possivel carregar o sistema de pagamento. Por favor, tente novamente.",
    "checkout.retryPayment": "Tentar Novamente",
    "checkout.paymentInitError": "Nao foi possivel configurar o pagamento. Por favor, tente novamente.",

    "notifications.title": "Notificacoes",
    "notifications.noNotifications": "Nenhuma notificacao",
    "notifications.noNotificationsDesc": "Voce esta em dia! Volte mais tarde para atualizacoes.",

    "notFound.title": "Pagina Nao Encontrada",
    "notFound.desc": "A pagina que voce esta procurando nao existe ou foi movida.",
    "notFound.goHome": "Ir para Inicio",

    "admin.title": "Painel Administrativo",
    "admin.users": "Usuarios",
    "admin.restaurants": "Restaurantes",
    "admin.services": "Servicos",
    "admin.orders": "Pedidos",
    "admin.events": "Eventos",
    "admin.businesses": "Empresas",
    "admin.announcements": "Anuncios",

    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.tryAgain": "Tentar novamente",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.back": "Voltar",
    "common.next": "Proximo",
    "common.submit": "Enviar",
    "common.close": "Fechar",

    "pendingApproval.title": "Registro em Analise",
    "pendingApproval.desc": "Seu registro como",
    "pendingApproval.descEnd": "esta sendo analisado pela nossa equipe.",
    "pendingApproval.wait": "Voce sera notificado assim que sua conta for aprovada. Isso geralmente leva 1-2 dias uteis.",
    "pendingApproval.vendorRole": "Restaurante / Vendedor de Comida",
    "pendingApproval.providerRole": "Prestador de Servicos",
    "pendingApproval.statusLabel": "Status",
    "pendingApproval.statusPending": "Aguardando Revisao",
    "pendingApproval.statusRejected": "Rejeitado",
    "pendingApproval.role": "Funcao",
    "pendingApproval.logout": "Sair",
    "pendingApproval.rejectedTitle": "Registro Nao Aprovado",
    "pendingApproval.rejectedDesc": "Infelizmente, seu registro como",
    "pendingApproval.rejectedDescEnd": "nao foi aprovado neste momento.",
    "pendingApproval.rejectedContact": "Entre em contato com o suporte se voce acredita que isso foi um erro.",

    "onboarding.pendingToast": "Registro Enviado",
    "onboarding.pendingToastDesc": "Seu registro esta aguardando aprovacao do administrador. Voce sera notificado quando aprovado.",

    "authDialog.title": "Bem-vindo ao BrazaDash",
    "authDialog.description": "Entre para pedir comida, reservar servicos e se conectar com a comunidade brasileira na California.",
    "authDialog.rolePrompt": "Como voce gostaria de usar o BrazaDash?",
    "authDialog.role.customer": "Cliente",
    "authDialog.role.customerDesc": "Peca comida, reserve servicos e explore a comunidade",
    "authDialog.role.vendor": "Dono de Restaurante",
    "authDialog.role.vendorDesc": "Cadastre seu restaurante e gerencie pedidos",
    "authDialog.role.provider": "Prestador de Servicos",
    "authDialog.role.providerDesc": "Ofereca seus servicos e gerencie reservas",
    "authDialog.continue": "Continuar",
    "authDialog.login": "Entrar",
    "authDialog.register": "Criar Conta",
    "authDialog.secure": "Protegido pela Autenticacao Replit",

    "onboarding.einNumber": "Numero EIN (CNPJ/Tax ID)",
    "onboarding.einNumberDesc": "Seu Numero de Identificacao do Empregador para fins fiscais (opcional).",
    "onboarding.bankInfoTitle": "Informacoes de Pagamento",
    "onboarding.bankInfoDesc": "Forneca seus dados bancarios para receber pagamentos de pedidos e reservas.",
    "onboarding.bankName": "Nome do Banco",
    "onboarding.bankNamePlaceholder": "ex. Bank of America, Chase",
    "onboarding.routingNumber": "Numero de Roteamento",
    "onboarding.routingNumberPlaceholder": "Numero de roteamento de 9 digitos",
    "onboarding.bankAccountNumber": "Numero da Conta",
    "onboarding.bankAccountPlaceholder": "Numero da conta bancaria",
    "onboarding.zelleInfo": "Zelle (Email ou Telefone)",
    "onboarding.zelleInfoPlaceholder": "Email ou telefone do Zelle",
    "onboarding.venmoInfo": "Usuario Venmo",
    "onboarding.venmoInfoPlaceholder": "@usuario",
    "onboarding.businessImage": "Imagem do Negocio",
    "onboarding.removeImage": "Remover",
    "onboarding.uploadBusinessImage": "Clique para enviar imagem do negocio",
    "onboarding.imageFormats": "JPEG, PNG, WebP, GIF (max 5MB)",
    "onboarding.imageTooLarge": "A imagem deve ter menos de 5MB",
    "onboarding.uploadFailed": "Falha ao enviar imagem",
    "onboarding.uploading": "Enviando...",

    "booking.book": "Reservar",
    "booking.requestBooking": "Solicitar Reserva",
    "booking.selectDateTime": "Selecione a data e horario preferidos para o servico",
    "booking.date": "Data",
    "booking.selectDate": "Selecionar data",
    "booking.time": "Horario",
    "booking.address": "Endereco",
    "booking.addressPlaceholder": "Endereco do local do servico",
    "booking.notes": "Observacoes (opcional)",
    "booking.notesPlaceholder": "Solicitacoes especiais ou detalhes...",
    "booking.paymentSummary": "Resumo do Pagamento",
    "booking.bookingFee": "Taxa de Reserva",
    "booking.total": "Total",
    "booking.payAndBook": "Pagar e Reservar",
    "booking.processing": "Processando...",
    "booking.loginToBook": "Entrar para Reservar",
    "booking.error": "Erro",
    "booking.checkoutFailed": "Falha ao criar sessao de pagamento.",
    "booking.paymentSuccess": "Pagamento Realizado!",
    "booking.bookingCreated": "Sua reserva foi criada. O prestador respondera em breve.",
    "booking.paymentCompleteFailed": "Falha ao concluir o pagamento da reserva.",

    "checkout.platformFee": "Taxa da Plataforma",

    "terminal.title": "Stripe Terminal (Pagamentos Presenciais)",
    "terminal.description": "Aceite pagamentos com cartao presenciais usando um leitor de cartao Stripe Terminal no seu restaurante.",
    "terminal.enableTerminal": "Ativar Pagamentos Presenciais",
    "terminal.enableDesc": "Ative o Stripe Terminal para aceitar pagamentos com cartao presencialmente.",
    "terminal.settingsUpdated": "Configuracoes do terminal atualizadas",
    "terminal.settingsUpdateFailed": "Falha ao atualizar configuracoes do terminal",
    "terminal.location": "Local do Terminal",
    "terminal.locationId": "ID do Local",
    "terminal.noLocation": "Nenhum local de terminal configurado ainda. Crie um para conectar leitores de cartao.",
    "terminal.setupLocation": "Configurar Local",
    "terminal.locationCreated": "Local do terminal criado com sucesso",
    "terminal.locationCreateFailed": "Falha ao criar local do terminal",
    "terminal.zipCode": "CEP",
    "terminal.zipRequired": "Insira um CEP valido de 5 digitos para o local do seu restaurante.",
    "terminal.connectedReaders": "Leitores de Cartao Conectados",
    "terminal.readersDesc": "Leitores de cartao registrados no local do seu terminal.",
    "terminal.noReaders": "Nenhum leitor de cartao encontrado",
    "terminal.noReadersHint": "Registre um leitor pelo Painel do Stripe ou use o app movel para descobrir leitores proximos.",
    "terminal.createCharge": "Criar Cobranca Presencial",
    "terminal.createChargeDesc": "Crie uma intencao de pagamento para um pagamento presencial com cartao. Use o app movel para coletar o pagamento.",
    "terminal.amount": "Valor (USD)",
    "terminal.chargeDescription": "Descricao",
    "terminal.chargeDescPlaceholder": "ex. Pedido da mesa 5",
    "terminal.createPaymentIntent": "Criar Intencao de Pagamento",
    "terminal.chargeCreated": "Intencao de pagamento criada",
    "terminal.paymentIntentId": "ID da Intencao de Pagamento",
    "terminal.chargeCreateFailed": "Falha ao criar intencao de pagamento",
    "terminal.tipping": "Gorjeta no Leitor",
    "terminal.tippingDesc": "Mostrar opcoes de gorjeta (15%, 20%, 25%) na tela do leitor de cartao antes de cobrar.",
    "terminal.tippingEnabled": "Gorjeta ativada",
    "terminal.tippingDisabled": "Gorjeta desativada",
    "terminal.tipIncluded": "Gorjeta incluida",
    "terminal.captureFailed": "Captura Falhou",
    "terminal.captureFailedDesc": "O pagamento foi autorizado mas nao foi capturado. Por favor, tente novamente.",
    "terminal.retryCapture": "Tentar Novamente",
    "terminal.paymentFailed": "Pagamento Falhou",
    "terminal.cardDeclined": "Cartao recusado ou removido. Por favor, tente novamente.",
    "terminal.customerEmail": "Email do Cliente (Opcional)",
    "terminal.customerEmailPlaceholder": "cliente@email.com (opcional)",
    "terminal.customerEmailHint": "Insira o email do cliente para enviar um recibo apos o pagamento",
    "common.dismiss": "Fechar",
    "common.refresh": "Atualizar",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("brazadash-lang") as Language) || "en";
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("brazadash-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
