import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.food": "Food",
    "nav.services": "Services",
    "nav.community": "Community",
    "nav.myOrders": "My Orders",
    "nav.myRestaurant": "My Restaurant",
    "nav.myServices": "My Services",
    "nav.getStarted": "Get Started",
    "nav.logout": "Log out",
    "nav.restaurantPortal": "Restaurant Portal",
    "nav.serviceProviderPortal": "Service Provider Portal",
    "nav.myBookings": "My Bookings",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.restaurantVendor": "Restaurant Vendor",
    "nav.serviceProvider": "Service Provider",
    "nav.customer": "Customer",

    "landing.badge": "Now serving California",
    "landing.heroTitle1": "Brazilian flavor",
    "landing.heroTitle2": "at your door",
    "landing.heroDesc": "Discover authentic Brazilian cuisine from your favorite restaurants. From feijoada to pao de queijo, experience the taste of Brazil right here in California.",
    "landing.orderNow": "Order Now",
    "landing.learnMore": "Learn More",
    "landing.securePayments": "Secure payments",
    "landing.fastDelivery": "Fast delivery",
    "landing.rating": "4.9 Rating",
    "landing.happyCustomers": "10k+ happy customers",
    "landing.whyChoose": "Why choose",
    "landing.whyChooseDesc": "We bring the authentic taste of Brazil to your doorstep with care and quality.",
    "landing.authenticCuisine": "Authentic Brazilian Cuisine",
    "landing.authenticCuisineDesc": "From traditional feijoada to street-style coxinhas, experience genuine Brazilian flavors prepared by passionate cooks.",
    "landing.localCommunity": "Local Community",
    "landing.localCommunityDesc": "Connect with Brazilian restaurants and home cooks right in your neighborhood. Support your local community.",
    "landing.fastDeliveryTitle": "Fast Delivery",
    "landing.fastDeliveryDesc": "Get your favorite Brazilian dishes delivered hot and fresh. Track your order in real-time from kitchen to door.",
    "landing.verifiedReviews": "Verified Reviews",
    "landing.verifiedReviewsDesc": "Make informed decisions with honest reviews from real customers. Every rating is from a verified order.",
    "landing.securePaymentsTitle": "Secure Payments",
    "landing.securePaymentsDesc": "Your transactions are protected with industry-standard encryption. Pay with confidence using your preferred method.",
    "landing.madeWithLove": "Made with Love",
    "landing.madeWithLoveDesc": "Every dish is prepared with the same love and care as a Brazilian home-cooked meal. Saudade never tasted so good.",
    "landing.readyToTaste": "Ready to taste Brazil?",
    "landing.readyToTasteDesc": "Join thousands of Brazilians in California enjoying authentic food from the comfort of their homes.",
    "landing.getStartedFree": "Get Started - It's Free",
    "landing.footer": "\u00a9 2024 BrazaDash. Made with love for the Brazilian community.",

    "onboarding.welcome": "Welcome to BrazaDash!",
    "onboarding.subtitle": "Welcome! How would you like to use the platform?",
    "onboarding.subtitlePt": "Como voc\u00ea gostaria de usar a plataforma?",
    "onboarding.customer": "Customer",
    "onboarding.customerSub": "Buy",
    "onboarding.customerDesc": "Browse restaurants, order food, book services, and explore the community.",
    "onboarding.vendor": "Restaurant / Food Vendor",
    "onboarding.vendorSub": "Sell Food",
    "onboarding.vendorDesc": "Manage your restaurant, create menus, and process food orders from customers.",
    "onboarding.provider": "Service Provider",
    "onboarding.providerSub": "Offer Services",
    "onboarding.providerDesc": "List your professional services, manage bookings, and grow your client base.",
    "onboarding.continue": "Continue",
    "onboarding.settingUp": "Setting up your account...",
    "onboarding.changeRole": "You can contact support later if you need to change your role.",
    "onboarding.welcomeToast": "Welcome to BrazaDash!",
    "onboarding.welcomeToastDesc": "Your account is ready. Let's get started!",
    "onboarding.error": "Something went wrong",
    "onboarding.errorDesc": "Please try again.",

    "home.badge": "Brazilian Community in California",
    "home.greeting": "Hello",
    "home.welcomeTo": "Welcome to BrazaDash",
    "home.heroDesc": "Your connection to the Brazilian community in California. Discover authentic restaurants, find trusted services, and connect with our community.",
    "home.orderFood": "Order Food",
    "home.findServices": "Find Services",
    "home.community": "Community",
    "home.popularServices": "Popular Services",
    "home.popularServicesDesc": "Popular services from our Brazilian community",
    "home.viewAll": "View All",
    "home.featuredProviders": "Featured Providers",
    "home.featuredRestaurants": "Featured Restaurants",
    "home.featuredRestaurantsDesc": "Discover the best Brazilian food in your area",
    "home.noRestaurants": "No restaurants yet",
    "home.noRestaurantsDesc": "Be the first to add your restaurant to BrazaDash!",
    "home.becomeVendor": "Become a Vendor",
    "home.testimonialsBadge": "Community Testimonials",
    "home.testimonialsTitle": "What Our Community Says",
    "home.testimonialsDesc": "What our community says about BrazaDash",
    "home.recentReviews": "Recent Reviews",
    "home.recentReviewsDesc": "Latest reviews from the community",
    "home.communityHub": "Community Hub",
    "home.upcomingEvents": "Upcoming Events",
    "home.viewAllEvents": "View all events",
    "home.noEvents": "No upcoming events",
    "home.businessDirectory": "Business Directory",
    "home.viewAllBusinesses": "View all businesses",
    "home.noBusinesses": "No businesses listed yet",
    "home.announcements": "Announcements",
    "home.noAnnouncements": "No announcements",
    "home.open": "Open",
    "home.closed": "Closed",
    "home.delivery": "delivery",
    "home.verified": "Verified",
    "home.food": "Food",
    "home.service": "Service",

    "home.cleaning": "Cleaning",
    "home.beauty": "Beauty",
    "home.legal": "Legal",
    "home.fitness": "Fitness",
    "home.auto": "Auto",
    "home.construction": "Construction",

    "restaurants.title": "Brazilian Restaurants",
    "restaurants.subtitle": "Discover authentic Brazilian food in your area",
    "restaurants.search": "Search restaurants...",
    "restaurants.all": "All",
    "restaurants.noResults": "No restaurants found",
    "restaurants.noResultsDesc": "Try adjusting your search or filter criteria.",
    "restaurants.open": "Open",
    "restaurants.closed": "Closed",

    "services.title": "Brazilian Services",
    "services.subtitle": "Find trusted Brazilian service providers in your area",
    "services.search": "Search services...",
    "services.allCategories": "All Categories",
    "services.noResults": "No service providers found",
    "services.noResultsDesc": "Try adjusting your search or filter criteria.",
    "services.startingAt": "Starting at",
    "services.viewProfile": "View Profile",
    "services.verified": "Verified",
    "services.reviews": "reviews",

    "community.title": "Community Hub",
    "community.subtitle": "Connect with the Brazilian community in California",
    "community.events": "Events",
    "community.businesses": "Businesses",
    "community.announcements": "Announcements",
    "community.featuredEvents": "Featured Events",
    "community.upcomingEvents": "Upcoming Events",
    "community.viewAllEvents": "View All Events",
    "community.noEvents": "No events found",
    "community.noEventsDesc": "Check back soon for upcoming community events!",
    "community.rsvp": "RSVP",
    "community.attending": "attending",
    "community.free": "Free",
    "community.businessDirectory": "Business Directory",
    "community.viewAllBusinesses": "View All Businesses",
    "community.noBusinesses": "No businesses found",
    "community.noBusinessesDesc": "Know a Brazilian business? Help us grow our directory!",
    "community.latestAnnouncements": "Latest Announcements",
    "community.noAnnouncements": "No announcements",
    "community.noAnnouncementsDesc": "Check back soon for community announcements!",

    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Looks like you haven't added any items yet. Explore our delicious Brazilian restaurants!",
    "cart.browseRestaurants": "Browse Restaurants",
    "cart.orderFrom": "Order from",
    "cart.items": "Items",
    "cart.clearCart": "Clear Cart",
    "cart.subtotal": "Subtotal",
    "cart.deliveryFee": "Delivery Fee",
    "cart.total": "Total",
    "cart.proceedToCheckout": "Proceed to Checkout",
    "cart.remove": "Remove",

    "orders.title": "My Orders",
    "orders.subtitle": "Track your food orders and delivery status",
    "orders.noOrders": "No orders yet",
    "orders.noOrdersDesc": "Start exploring our restaurants and place your first order!",
    "orders.browseRestaurants": "Browse Restaurants",
    "orders.orderNumber": "Order",
    "orders.items": "items",
    "orders.viewDetails": "View Details",
    "orders.pending": "Pending",
    "orders.confirmed": "Confirmed",
    "orders.preparing": "Preparing",
    "orders.ready": "Ready",
    "orders.outForDelivery": "Out for Delivery",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",

    "vendor.dashboard": "Restaurant Dashboard",
    "vendor.createRestaurant": "Create Your Restaurant",
    "vendor.restaurantName": "Restaurant Name",
    "vendor.description": "Description",
    "vendor.cuisine": "Cuisine Type",
    "vendor.address": "Address",
    "vendor.phone": "Phone",
    "vendor.deliveryFee": "Delivery Fee",
    "vendor.create": "Create Restaurant",
    "vendor.creating": "Creating...",
    "vendor.orders": "Orders",
    "vendor.menu": "Menu",
    "vendor.newOrders": "New Orders",
    "vendor.activeOrders": "Active Orders",
    "vendor.completed": "Completed",
    "vendor.noOrders": "No orders yet",
    "vendor.accept": "Accept Order",
    "vendor.decline": "Decline",
    "vendor.startPreparing": "Start Preparing",
    "vendor.readyForPickup": "Ready for Pickup",
    "vendor.outForDelivery": "Out for Delivery",
    "vendor.markDelivered": "Mark Delivered",
    "vendor.addMenuItem": "Add Item",
    "vendor.itemName": "Item Name",
    "vendor.price": "Price",
    "vendor.category": "Category",
    "vendor.save": "Save",
    "vendor.pending": "Pending",
    "vendor.active": "Active",
    "vendor.rating": "Rating",
    "vendor.menuItems": "Menu Items",
    "vendor.restaurantOpen": "Restaurant is open",
    "vendor.restaurantClosed": "Restaurant is closed",
    "vendor.newOrder": "New Order",
    "vendor.orderConfirmed": "Confirmed",
    "vendor.orderPreparing": "Preparing",
    "vendor.orderReady": "Ready for Pickup",
    "vendor.orderOutForDelivery": "Out for Delivery",
    "vendor.orderDelivered": "Delivered",
    "vendor.orderCancelled": "Cancelled",

    "checkout.title": "Checkout",
    "checkout.deliveryAddress": "Delivery Address",
    "checkout.fullAddress": "Full Address",
    "checkout.addressPlaceholder": "Enter your delivery address...",
    "checkout.deliveryInstructions": "Delivery Instructions (Optional)",
    "checkout.instructionsPlaceholder": "Apartment number, gate code, etc...",
    "checkout.addTip": "Add a Tip",
    "checkout.noTip": "No tip",
    "checkout.paymentMethod": "Payment Method",
    "checkout.loadingPayment": "Loading payment...",
    "checkout.enterAddress": "Please enter your delivery address above to proceed with payment.",
    "checkout.preparingPayment": "Preparing payment form...",
    "checkout.loadingPaymentForm": "Loading payment form...",
    "checkout.processingPayment": "Processing Payment...",
    "checkout.securePayment": "Payments are securely processed by Stripe",
    "checkout.orderSummary": "Order Summary",
    "checkout.tip": "Tip",
    "checkout.payWithStripe": "Pay with Stripe",
    "checkout.processing": "Processing...",
    "checkout.notes": "Special Instructions",
    "checkout.paymentFailed": "Payment Failed",
    "checkout.paymentFailedDesc": "Your payment could not be processed. Please try again.",
    "checkout.orderConfirmed": "Order Confirmed!",
    "checkout.orderConfirmedDesc": "Thank you for your order! Your food is being prepared and will be on its way soon.",
    "checkout.orderId": "Order ID",
    "checkout.viewOrder": "View Order",
    "checkout.continueShopping": "Continue Shopping",
    "checkout.processingOrder": "Processing your order...",
    "checkout.confirmingPayment": "Please wait while we confirm your payment.",
    "checkout.somethingWrong": "Something went wrong",
    "checkout.orderError": "We couldn't process your order. Please contact support if you were charged.",
    "checkout.returnToCart": "Return to Cart",
    "checkout.initError": "Failed to initialize payment. Please try again.",
    "checkout.orderCreateError": "Payment was successful but order creation failed. Please contact support.",

    "notifications.title": "Notifications",
    "notifications.noNotifications": "No notifications",
    "notifications.noNotificationsDesc": "You're all caught up! Check back later for updates.",

    "notFound.title": "Page Not Found",
    "notFound.desc": "The page you're looking for doesn't exist or has been moved.",
    "notFound.goHome": "Go Home",

    "admin.title": "Admin Dashboard",
    "admin.users": "Users",
    "admin.restaurants": "Restaurants",
    "admin.services": "Services",
    "admin.orders": "Orders",
    "admin.events": "Events",
    "admin.businesses": "Businesses",
    "admin.announcements": "Announcements",

    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.tryAgain": "Try again",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.close": "Close",

    "pendingApproval.title": "Registration Under Review",
    "pendingApproval.desc": "Your registration as a",
    "pendingApproval.descEnd": "is currently being reviewed by our team.",
    "pendingApproval.wait": "You will be notified once your account has been approved. This usually takes 1-2 business days.",
    "pendingApproval.vendorRole": "Restaurant / Food Vendor",
    "pendingApproval.providerRole": "Service Provider",
    "pendingApproval.statusLabel": "Status",
    "pendingApproval.statusPending": "Pending Review",
    "pendingApproval.statusRejected": "Rejected",
    "pendingApproval.role": "Role",
    "pendingApproval.logout": "Sign Out",
    "pendingApproval.rejectedTitle": "Registration Not Approved",
    "pendingApproval.rejectedDesc": "Unfortunately, your registration as a",
    "pendingApproval.rejectedDescEnd": "was not approved at this time.",
    "pendingApproval.rejectedContact": "Please contact support if you believe this was a mistake.",

    "onboarding.pendingToast": "Registration Submitted",
    "onboarding.pendingToastDesc": "Your registration is pending admin approval. You'll be notified once approved.",
  },
  pt: {
    "nav.home": "Inicio",
    "nav.food": "Comida",
    "nav.services": "Servicos",
    "nav.community": "Comunidade",
    "nav.myOrders": "Meus Pedidos",
    "nav.myRestaurant": "Meu Restaurante",
    "nav.myServices": "Meus Servicos",
    "nav.getStarted": "Comecar",
    "nav.logout": "Sair",
    "nav.restaurantPortal": "Portal do Restaurante",
    "nav.serviceProviderPortal": "Portal de Servicos",
    "nav.myBookings": "Minhas Reservas",
    "nav.adminDashboard": "Painel Admin",
    "nav.restaurantVendor": "Restaurante",
    "nav.serviceProvider": "Prestador de Servicos",
    "nav.customer": "Cliente",

    "landing.badge": "Atendendo a California",
    "landing.heroTitle1": "Sabor brasileiro",
    "landing.heroTitle2": "na sua porta",
    "landing.heroDesc": "Descubra a autentica culinaria brasileira dos seus restaurantes favoritos. De feijoada a pao de queijo, experimente o sabor do Brasil aqui na California.",
    "landing.orderNow": "Pedir Agora",
    "landing.learnMore": "Saiba Mais",
    "landing.securePayments": "Pagamentos seguros",
    "landing.fastDelivery": "Entrega rapida",
    "landing.rating": "4.9 Avaliacao",
    "landing.happyCustomers": "10k+ clientes satisfeitos",
    "landing.whyChoose": "Por que escolher",
    "landing.whyChooseDesc": "Trazemos o autentico sabor do Brasil ate a sua porta com cuidado e qualidade.",
    "landing.authenticCuisine": "Culinaria Brasileira Autentica",
    "landing.authenticCuisineDesc": "Da tradicional feijoada as coxinhas de rua, experimente sabores genuinos brasileiros preparados por cozinheiros apaixonados.",
    "landing.localCommunity": "Comunidade Local",
    "landing.localCommunityDesc": "Conecte-se com restaurantes e cozinheiros brasileiros no seu bairro. Apoie sua comunidade local.",
    "landing.fastDeliveryTitle": "Entrega Rapida",
    "landing.fastDeliveryDesc": "Receba seus pratos brasileiros favoritos quentes e frescos. Acompanhe seu pedido em tempo real da cozinha ate a porta.",
    "landing.verifiedReviews": "Avaliacoes Verificadas",
    "landing.verifiedReviewsDesc": "Tome decisoes informadas com avaliacoes honestas de clientes reais. Cada nota e de um pedido verificado.",
    "landing.securePaymentsTitle": "Pagamentos Seguros",
    "landing.securePaymentsDesc": "Suas transacoes sao protegidas com criptografia padrao da industria. Pague com confianca usando seu metodo preferido.",
    "landing.madeWithLove": "Feito com Amor",
    "landing.madeWithLoveDesc": "Cada prato e preparado com o mesmo amor e cuidado de uma refeicao caseira brasileira. Saudade nunca teve sabor tao bom.",
    "landing.readyToTaste": "Pronto para experimentar o Brasil?",
    "landing.readyToTasteDesc": "Junte-se a milhares de brasileiros na California aproveitando comida autentica no conforto de suas casas.",
    "landing.getStartedFree": "Comecar - E Gratis",
    "landing.footer": "\u00a9 2024 BrazaDash. Feito com amor para a comunidade brasileira.",

    "onboarding.welcome": "Bem-vindo ao BrazaDash!",
    "onboarding.subtitle": "Como voce gostaria de usar a plataforma?",
    "onboarding.subtitlePt": "",
    "onboarding.customer": "Cliente",
    "onboarding.customerSub": "Comprar",
    "onboarding.customerDesc": "Navegue pelos restaurantes, peca comida, reserve servicos e explore a comunidade.",
    "onboarding.vendor": "Restaurante / Vendedor de Comida",
    "onboarding.vendorSub": "Vender Comida",
    "onboarding.vendorDesc": "Gerencie seu restaurante, crie cardapios e processe pedidos de comida dos clientes.",
    "onboarding.provider": "Prestador de Servicos",
    "onboarding.providerSub": "Oferecer Servicos",
    "onboarding.providerDesc": "Liste seus servicos profissionais, gerencie reservas e amplie sua base de clientes.",
    "onboarding.continue": "Continuar",
    "onboarding.settingUp": "Configurando sua conta...",
    "onboarding.changeRole": "Voce pode entrar em contato com o suporte depois se precisar mudar sua funcao.",
    "onboarding.welcomeToast": "Bem-vindo ao BrazaDash!",
    "onboarding.welcomeToastDesc": "Sua conta esta pronta. Vamos comecar!",
    "onboarding.error": "Algo deu errado",
    "onboarding.errorDesc": "Por favor, tente novamente.",

    "home.badge": "Comunidade Brasileira na California",
    "home.greeting": "Ola",
    "home.welcomeTo": "Bem-vindo ao BrazaDash",
    "home.heroDesc": "Sua conexao com a comunidade brasileira na California. Descubra restaurantes autenticos, encontre servicos de confianca e conecte-se com a nossa comunidade.",
    "home.orderFood": "Pedir Comida",
    "home.findServices": "Encontrar Servicos",
    "home.community": "Comunidade",
    "home.popularServices": "Servicos Populares",
    "home.popularServicesDesc": "Servicos populares da nossa comunidade brasileira",
    "home.viewAll": "Ver Todos",
    "home.featuredProviders": "Provedores em Destaque",
    "home.featuredRestaurants": "Restaurantes em Destaque",
    "home.featuredRestaurantsDesc": "Descubra a melhor comida brasileira na sua regiao",
    "home.noRestaurants": "Nenhum restaurante ainda",
    "home.noRestaurantsDesc": "Seja o primeiro a adicionar seu restaurante no BrazaDash!",
    "home.becomeVendor": "Seja um Vendedor",
    "home.testimonialsBadge": "Depoimentos da Comunidade",
    "home.testimonialsTitle": "O Que Nossa Comunidade Diz",
    "home.testimonialsDesc": "O que nossa comunidade diz sobre o BrazaDash",
    "home.recentReviews": "Avaliacoes Recentes",
    "home.recentReviewsDesc": "Ultimas avaliacoes da comunidade",
    "home.communityHub": "Hub da Comunidade",
    "home.upcomingEvents": "Proximos Eventos",
    "home.viewAllEvents": "Ver todos os eventos",
    "home.noEvents": "Nenhum evento proximo",
    "home.businessDirectory": "Diretorio de Empresas",
    "home.viewAllBusinesses": "Ver todas as empresas",
    "home.noBusinesses": "Nenhuma empresa listada ainda",
    "home.announcements": "Anuncios",
    "home.noAnnouncements": "Nenhum anuncio",
    "home.open": "Aberto",
    "home.closed": "Fechado",
    "home.delivery": "entrega",
    "home.verified": "Verificado",
    "home.food": "Comida",
    "home.service": "Servico",

    "home.cleaning": "Limpeza",
    "home.beauty": "Beleza",
    "home.legal": "Legal",
    "home.fitness": "Fitness",
    "home.auto": "Auto",
    "home.construction": "Construcao",

    "restaurants.title": "Restaurantes Brasileiros",
    "restaurants.subtitle": "Descubra comida brasileira autentica na sua regiao",
    "restaurants.search": "Buscar restaurantes...",
    "restaurants.all": "Todos",
    "restaurants.noResults": "Nenhum restaurante encontrado",
    "restaurants.noResultsDesc": "Tente ajustar sua busca ou filtros.",
    "restaurants.open": "Aberto",
    "restaurants.closed": "Fechado",

    "services.title": "Servicos Brasileiros",
    "services.subtitle": "Encontre prestadores de servicos brasileiros de confianca na sua regiao",
    "services.search": "Buscar servicos...",
    "services.allCategories": "Todas as Categorias",
    "services.noResults": "Nenhum prestador de servicos encontrado",
    "services.noResultsDesc": "Tente ajustar sua busca ou filtros.",
    "services.startingAt": "A partir de",
    "services.viewProfile": "Ver Perfil",
    "services.verified": "Verificado",
    "services.reviews": "avaliacoes",

    "community.title": "Hub da Comunidade",
    "community.subtitle": "Conecte-se com a comunidade brasileira na California",
    "community.events": "Eventos",
    "community.businesses": "Empresas",
    "community.announcements": "Anuncios",
    "community.featuredEvents": "Eventos em Destaque",
    "community.upcomingEvents": "Proximos Eventos",
    "community.viewAllEvents": "Ver Todos os Eventos",
    "community.noEvents": "Nenhum evento encontrado",
    "community.noEventsDesc": "Volte em breve para eventos da comunidade!",
    "community.rsvp": "Confirmar Presenca",
    "community.attending": "confirmados",
    "community.free": "Gratis",
    "community.businessDirectory": "Diretorio de Empresas",
    "community.viewAllBusinesses": "Ver Todas as Empresas",
    "community.noBusinesses": "Nenhuma empresa encontrada",
    "community.noBusinessesDesc": "Conhece um negocio brasileiro? Ajude-nos a expandir nosso diretorio!",
    "community.latestAnnouncements": "Ultimos Anuncios",
    "community.noAnnouncements": "Nenhum anuncio",
    "community.noAnnouncementsDesc": "Volte em breve para anuncios da comunidade!",

    "cart.title": "Seu Carrinho",
    "cart.empty": "Seu carrinho esta vazio",
    "cart.emptyDesc": "Parece que voce ainda nao adicionou nenhum item. Explore nossos deliciosos restaurantes brasileiros!",
    "cart.browseRestaurants": "Ver Restaurantes",
    "cart.orderFrom": "Pedido de",
    "cart.items": "Itens",
    "cart.clearCart": "Limpar Carrinho",
    "cart.subtotal": "Subtotal",
    "cart.deliveryFee": "Taxa de Entrega",
    "cart.total": "Total",
    "cart.proceedToCheckout": "Ir para Pagamento",
    "cart.remove": "Remover",

    "orders.title": "Meus Pedidos",
    "orders.subtitle": "Acompanhe seus pedidos de comida e status de entrega",
    "orders.noOrders": "Nenhum pedido ainda",
    "orders.noOrdersDesc": "Comece explorando nossos restaurantes e faca seu primeiro pedido!",
    "orders.browseRestaurants": "Ver Restaurantes",
    "orders.orderNumber": "Pedido",
    "orders.items": "itens",
    "orders.viewDetails": "Ver Detalhes",
    "orders.pending": "Pendente",
    "orders.confirmed": "Confirmado",
    "orders.preparing": "Preparando",
    "orders.ready": "Pronto",
    "orders.outForDelivery": "Saiu para Entrega",
    "orders.delivered": "Entregue",
    "orders.cancelled": "Cancelado",

    "vendor.dashboard": "Painel do Restaurante",
    "vendor.createRestaurant": "Crie Seu Restaurante",
    "vendor.restaurantName": "Nome do Restaurante",
    "vendor.description": "Descricao",
    "vendor.cuisine": "Tipo de Culinaria",
    "vendor.address": "Endereco",
    "vendor.phone": "Telefone",
    "vendor.deliveryFee": "Taxa de Entrega",
    "vendor.create": "Criar Restaurante",
    "vendor.creating": "Criando...",
    "vendor.orders": "Pedidos",
    "vendor.menu": "Cardapio",
    "vendor.newOrders": "Novos Pedidos",
    "vendor.activeOrders": "Pedidos Ativos",
    "vendor.completed": "Concluidos",
    "vendor.noOrders": "Nenhum pedido ainda",
    "vendor.accept": "Aceitar Pedido",
    "vendor.decline": "Recusar",
    "vendor.startPreparing": "Comecar a Preparar",
    "vendor.readyForPickup": "Pronto para Retirada",
    "vendor.outForDelivery": "Saiu para Entrega",
    "vendor.markDelivered": "Marcar como Entregue",
    "vendor.addMenuItem": "Adicionar Item",
    "vendor.itemName": "Nome do Item",
    "vendor.price": "Preco",
    "vendor.category": "Categoria",
    "vendor.save": "Salvar",
    "vendor.pending": "Pendente",
    "vendor.active": "Ativo",
    "vendor.rating": "Avaliacao",
    "vendor.menuItems": "Itens do Cardapio",
    "vendor.restaurantOpen": "Restaurante esta aberto",
    "vendor.restaurantClosed": "Restaurante esta fechado",
    "vendor.newOrder": "Novo Pedido",
    "vendor.orderConfirmed": "Confirmado",
    "vendor.orderPreparing": "Preparando",
    "vendor.orderReady": "Pronto para Retirada",
    "vendor.orderOutForDelivery": "Saiu para Entrega",
    "vendor.orderDelivered": "Entregue",
    "vendor.orderCancelled": "Cancelado",

    "checkout.title": "Pagamento",
    "checkout.deliveryAddress": "Endereco de Entrega",
    "checkout.fullAddress": "Endereco Completo",
    "checkout.addressPlaceholder": "Digite seu endereco de entrega...",
    "checkout.deliveryInstructions": "Instrucoes de Entrega (Opcional)",
    "checkout.instructionsPlaceholder": "Numero do apartamento, codigo do portao, etc...",
    "checkout.addTip": "Adicionar Gorjeta",
    "checkout.noTip": "Sem gorjeta",
    "checkout.paymentMethod": "Metodo de Pagamento",
    "checkout.loadingPayment": "Carregando pagamento...",
    "checkout.enterAddress": "Por favor, insira seu endereco de entrega acima para prosseguir com o pagamento.",
    "checkout.preparingPayment": "Preparando formulario de pagamento...",
    "checkout.loadingPaymentForm": "Carregando formulario de pagamento...",
    "checkout.processingPayment": "Processando Pagamento...",
    "checkout.securePayment": "Pagamentos processados com seguranca pelo Stripe",
    "checkout.orderSummary": "Resumo do Pedido",
    "checkout.tip": "Gorjeta",
    "checkout.payWithStripe": "Pagar com Stripe",
    "checkout.processing": "Processando...",
    "checkout.notes": "Instrucoes Especiais",
    "checkout.paymentFailed": "Pagamento Falhou",
    "checkout.paymentFailedDesc": "Seu pagamento nao pôde ser processado. Por favor, tente novamente.",
    "checkout.orderConfirmed": "Pedido Confirmado!",
    "checkout.orderConfirmedDesc": "Obrigado pelo seu pedido! Sua comida esta sendo preparada e logo estara a caminho.",
    "checkout.orderId": "ID do Pedido",
    "checkout.viewOrder": "Ver Pedido",
    "checkout.continueShopping": "Continuar Comprando",
    "checkout.processingOrder": "Processando seu pedido...",
    "checkout.confirmingPayment": "Por favor, aguarde enquanto confirmamos seu pagamento.",
    "checkout.somethingWrong": "Algo deu errado",
    "checkout.orderError": "Nao foi possivel processar seu pedido. Entre em contato com o suporte se voce foi cobrado.",
    "checkout.returnToCart": "Voltar ao Carrinho",
    "checkout.initError": "Falha ao inicializar pagamento. Por favor, tente novamente.",
    "checkout.orderCreateError": "Pagamento realizado com sucesso, mas a criacao do pedido falhou. Entre em contato com o suporte.",

    "notifications.title": "Notificacoes",
    "notifications.noNotifications": "Nenhuma notificacao",
    "notifications.noNotificationsDesc": "Voce esta em dia! Volte mais tarde para atualizacoes.",

    "notFound.title": "Pagina Nao Encontrada",
    "notFound.desc": "A pagina que voce esta procurando nao existe ou foi movida.",
    "notFound.goHome": "Ir para Inicio",

    "admin.title": "Painel Administrativo",
    "admin.users": "Usuarios",
    "admin.restaurants": "Restaurantes",
    "admin.services": "Servicos",
    "admin.orders": "Pedidos",
    "admin.events": "Eventos",
    "admin.businesses": "Empresas",
    "admin.announcements": "Anuncios",

    "common.loading": "Carregando...",
    "common.error": "Algo deu errado",
    "common.tryAgain": "Tentar novamente",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.all": "Todos",
    "common.back": "Voltar",
    "common.next": "Proximo",
    "common.submit": "Enviar",
    "common.close": "Fechar",

    "pendingApproval.title": "Registro em Analise",
    "pendingApproval.desc": "Seu registro como",
    "pendingApproval.descEnd": "esta sendo analisado pela nossa equipe.",
    "pendingApproval.wait": "Voce sera notificado assim que sua conta for aprovada. Isso geralmente leva 1-2 dias uteis.",
    "pendingApproval.vendorRole": "Restaurante / Vendedor de Comida",
    "pendingApproval.providerRole": "Prestador de Servicos",
    "pendingApproval.statusLabel": "Status",
    "pendingApproval.statusPending": "Aguardando Revisao",
    "pendingApproval.statusRejected": "Rejeitado",
    "pendingApproval.role": "Funcao",
    "pendingApproval.logout": "Sair",
    "pendingApproval.rejectedTitle": "Registro Nao Aprovado",
    "pendingApproval.rejectedDesc": "Infelizmente, seu registro como",
    "pendingApproval.rejectedDescEnd": "nao foi aprovado neste momento.",
    "pendingApproval.rejectedContact": "Entre em contato com o suporte se voce acredita que isso foi um erro.",

    "onboarding.pendingToast": "Registro Enviado",
    "onboarding.pendingToastDesc": "Seu registro esta aguardando aprovacao do administrador. Voce sera notificado quando aprovado.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("brazadash-lang") as Language) || "en";
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("brazadash-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
